// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqOU5nt7pgSpGWbWJIDhkA_V7K2nLQeCk',
    appId: '1:664330226574:web:49c664305439be12f872df',
    messagingSenderId: '664330226574',
    projectId: 'chat-app-bb8e7',
    authDomain: 'chat-app-bb8e7.firebaseapp.com',
    storageBucket: 'chat-app-bb8e7.appspot.com',
    measurementId: 'G-G8FS165H6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy5X8cdWv2D7In-3sZh5MNjU4vs9PlJoE',
    appId: '1:664330226574:android:ee4361d5aad1d7f4f872df',
    messagingSenderId: '664330226574',
    projectId: 'chat-app-bb8e7',
    storageBucket: 'chat-app-bb8e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBex9rsbSKddDcze6JCw6UcbX6yoHPkBLw',
    appId: '1:664330226574:ios:2c976d75989cbdf5f872df',
    messagingSenderId: '664330226574',
    projectId: 'chat-app-bb8e7',
    storageBucket: 'chat-app-bb8e7.appspot.com',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBex9rsbSKddDcze6JCw6UcbX6yoHPkBLw',
    appId: '1:664330226574:ios:60fa0171443035abf872df',
    messagingSenderId: '664330226574',
    projectId: 'chat-app-bb8e7',
    storageBucket: 'chat-app-bb8e7.appspot.com',
    iosBundleId: 'com.example.messageBoardApp.RunnerTests',
  );
}
