// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKR8GXQbbif2cWkV6iQzys33cxE57D-gM',
    appId: '1:431616007754:web:8c75c25cdfb171571950b3',
    messagingSenderId: '431616007754',
    projectId: 'shopping-app-7e989',
    authDomain: 'shopping-app-7e989.firebaseapp.com',
    databaseURL: 'https://shopping-app-7e989-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-7e989.appspot.com',
    measurementId: 'G-LTD2G5MPL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4S5cluxUWXFAxl2tQZxYx0k6Yg12z_Tc',
    appId: '1:431616007754:android:9db3741495f7d1531950b3',
    messagingSenderId: '431616007754',
    projectId: 'shopping-app-7e989',
    databaseURL: 'https://shopping-app-7e989-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-7e989.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQL0mva1kqerGM3ejf9Ee-WSod3BBmnak',
    appId: '1:431616007754:ios:4c8a1ddaf81892ed1950b3',
    messagingSenderId: '431616007754',
    projectId: 'shopping-app-7e989',
    databaseURL: 'https://shopping-app-7e989-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-7e989.appspot.com',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQL0mva1kqerGM3ejf9Ee-WSod3BBmnak',
    appId: '1:431616007754:ios:25028d1e1b6e429b1950b3',
    messagingSenderId: '431616007754',
    projectId: 'shopping-app-7e989',
    databaseURL: 'https://shopping-app-7e989-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-app-7e989.appspot.com',
    iosBundleId: 'com.example.messageBoardApp.RunnerTests',
  );
}
